;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.DoubleJump",DevComment="")
+GameplayTagList=(Tag="Ability.DropIntro",DevComment="낙하 인트로 연출")
+GameplayTagList=(Tag="Ability.Fire",DevComment="")
+GameplayTagList=(Tag="Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Reload",DevComment="")
+GameplayTagList=(Tag="Ability.Shoot",DevComment="")
+GameplayTagList=(Tag="Ability.Skill1",DevComment="")
+GameplayTagList=(Tag="Ability.Skill2",DevComment="")
+GameplayTagList=(Tag="Ability.Sprint",DevComment="")
+GameplayTagList=(Tag="Ability.Ultimate",DevComment="")
+GameplayTagList=(Tag="Cooldown.Skill1",DevComment="Q 스킬 쿨다운")
+GameplayTagList=(Tag="Cooldown.Skill2",DevComment="E 스킬 쿨다운")
+GameplayTagList=(Tag="Event.Death",DevComment="사망 이벤트")
+GameplayTagList=(Tag="Event.Hit",DevComment="피격 이벤트")
+GameplayTagList=(Tag="Event.Landed",DevComment="착지 이벤트")
+GameplayTagList=(Tag="GameplayEffect.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Heal",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.StaminaDrain",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.UltGaugeCharge",DevComment="")
+GameplayTagList=(Tag="InputTag.ADS",DevComment="조준 (RMB)")
+GameplayTagList=(Tag="InputTag.Fire",DevComment="")
+GameplayTagList=(Tag="InputTag.Jump",DevComment="점프 / 2단 점프")
+GameplayTagList=(Tag="InputTag.Look",DevComment="마우스 시점")
+GameplayTagList=(Tag="InputTag.Move",DevComment="WASD 이동")
+GameplayTagList=(Tag="InputTag.Reload",DevComment="재장전 (R)")
+GameplayTagList=(Tag="InputTag.Scoreboard",DevComment="")
+GameplayTagList=(Tag="InputTag.Shoot",DevComment="사격 (LMB)")
+GameplayTagList=(Tag="InputTag.Skill1",DevComment="스킬 1 (Q)")
+GameplayTagList=(Tag="InputTag.Skill2",DevComment="스킬 2 (E)")
+GameplayTagList=(Tag="InputTag.Sprint",DevComment="달리기 (Shift)")
+GameplayTagList=(Tag="InputTag.Ultimate",DevComment="궁극기 (F)")
+GameplayTagList=(Tag="Status.ADS",DevComment="조준 중")
+GameplayTagList=(Tag="Status.Dead",DevComment="사망 상태")
+GameplayTagList=(Tag="Status.DoubleJumpUsed",DevComment="2단 점프 사용됨")
+GameplayTagList=(Tag="Status.InAir",DevComment="공중 상태")
+GameplayTagList=(Tag="Status.Sprinting",DevComment="달리기 중")
+GameplayTagList=(Tag="UI.Layer.Game",DevComment="인게임 HUD 레이어")
+GameplayTagList=(Tag="UI.Layer.GameMenu",DevComment="일시정지/스코어보드 레이어")
+GameplayTagList=(Tag="UI.Layer.Menu",DevComment="메인/로비 메뉴 레이어")
+GameplayTagList=(Tag="UI.Layer.Modal",DevComment="모달/확인 다이얼로그 레이어")

