#include "Utility/LastFPSTags.h"

namespace LastFPSGameplayTags
{
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Character_State_Dead, "Character.State.Dead", "Character is dead")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Character_State_Crouched, "Character.State.Crouched", "Character is crouching")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Character_Type_Boss, "Character.Type.Boss", "보스 캐릭터 분류")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Character_State_Sprinting, "Character.State.Sprinting", "캐릭터가 달리는 상태")

UE_DEFINE_GAMEPLAY_TAG_COMMENT(Status_AuraDamageCooldown, "Status.AuraDamageCooldown", "오라 데미지 재적용 대기 상태")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Status_Freeze, "Status.Freeze", "빙결 상태")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Status_FreezeStack, "Status.FreezeStack", "빙결 누적 상태")

UE_DEFINE_GAMEPLAY_TAG_COMMENT(Status_Movement_Slow, "Status.Movement.Slow", "이동 속도 감소 효과가 활성화된 상태")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Status_Movement_SpeedBoost, "Status.Movement.SpeedBoost", "이동속도 증가 효과가 활성화된 상태")

UE_DEFINE_GAMEPLAY_TAG_COMMENT(Cooldown_Skill_Dash, "Cooldown.Skill.Dash", "Dash cooldown")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Cooldown_Skill1, "Cooldown.Skill1", "Skill 1 cooldown")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Cooldown_Skill2, "Cooldown.Skill2", "Skill 2 cooldown")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Cooldown_Skill3, "Cooldown.Skill3", "Skill 3 cooldown")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Cooldown_Ultimate, "Cooldown.Ultimate", "Ultimate cooldown")

UE_DEFINE_GAMEPLAY_TAG_COMMENT(SetByCaller_Damage, "SetByCaller.Damage", "SetByCaller damage magnitude")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(SetByCaller_CriticalHit, "SetByCaller.CriticalHit", "SetByCaller critical hit flag")

UE_DEFINE_GAMEPLAY_TAG_COMMENT(Skill_Parameter_AreaDuration, "Skill.Parameter.AreaDuration", "개별 피해 영역의 유지 시간")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Skill_Parameter_DamageInterval, "Skill.Parameter.DamageInterval", "반복 피해 적용 간격")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Skill_Parameter_ConeAngle, "Skill.Parameter.ConeAngle", "부채꼴 스킬의 전체 각도")

UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Montage_AbilityCommit, "Event.Montage.Ability.Commit", "Commit an ability from an ability montage")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Montage_AbilityEnd, "Event.Montage.Ability.End", "End an ability from an ability montage")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Montage_ProjectileSpawn, "Event.Montage.Projectile.Spawn", "Spawn a projectile from an ability montage")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Montage_MeleeTrace, "Event.Montage.Melee.Trace", "근접 연속 판정 이벤트")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Montage_MeleeTrace_Begin, "Event.Montage.Melee.Trace.Begin", "근접 연속 판정 시작")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Montage_MeleeTrace_Tick, "Event.Montage.Melee.Trace.Tick", "근접 연속 판정 갱신")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Montage_MeleeTrace_End, "Event.Montage.Melee.Trace.End", "근접 연속 판정 종료")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Montage_MeleeHit, "Event.Montage.Melee.Hit", "적 근접 공격 판정 실행")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Montage_GroundSlamImpact, "Event.Montage.GroundSlam.Impact", "보스 지면 강타 충격 판정 실행")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Montage_ViolaIceAuraEffect, "Event.Montage.ViolaIceAura.Effect", "비올라 얼음 오라 이펙트 실행")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Montage_ViolaFrostStormEffect, "Event.Montage.ViolaFrostStorm.Effect", "비올라 냉기 폭풍 효과 실행")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Montage_IceStormSpawn, "Event.Montage.IceStorm.Spawn", "Spawn an ice storm area from an ability montage")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Montage_GrapplingHookPull, "Event.Montage.GrapplingHook.Pull", "그래플링 훅 당김 시작")

UE_DEFINE_GAMEPLAY_TAG_COMMENT(UI_HUD_Visible, "UI.HUD.Visible", "HUD visibility status")

UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_Move, "InputTag.Move", "Move input")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_Look, "InputTag.Look", "Look input")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_Sprint, "InputTag.Sprint", "Sprint input")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_ADS, "InputTag.ADS", "ADS input")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_Jump, "InputTag.Jump", "Jump input")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_Dash, "InputTag.Dash", "Dash input")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_Fire, "InputTag.Fire", "Fire input")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_Reload, "InputTag.Reload", "Reload input")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_Scoreboard, "InputTag.Scoreboard", "Scoreboard input")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_Skill1, "InputTag.Skill1", "Skill 1 input")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_Skill2, "InputTag.Skill2", "Skill 2 input")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_Skill3, "InputTag.Skill3", "Skill 3 input")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_Ultimate, "InputTag.Ultimate", "Ultimate input")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Input_GrapplingHook, "InputTag.GrapplingHook", "그래플링 훅 입력")

UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Sprint, "Ability.Sprint", "Sprint ability")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Jump, "Ability.Jump", "Jump ability")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_DoubleJump, "Ability.DoubleJump", "Double jump ability")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Dash, "Ability.Dash", "Dash ability")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Fire, "Ability.Fire", "Fire ability")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Reload, "Ability.Reload", "Reload ability")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Skill1, "Ability.Skill1", "Skill 1 ability")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Skill2, "Ability.Skill2", "Skill 2 ability")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Skill3, "Ability.Skill3", "Skill 3 ability")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Ultimate, "Ability.Ultimate", "Ultimate ability")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_GrapplingHook, "Ability.GrapplingHook", "지형 그래플링 훅 어빌리티")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_ProbePassive, "Ability.Passive.Probe", "프로브 패시브 어빌리티")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Trigger_SpawnProbe, "Ability.Trigger.SpawnProbe", "프로브 생성 트리거 어빌리티")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Enemy_Shoot, "Ability.Enemy.Shoot", "적 AI 원거리 발사 공격")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Enemy_Melee, "Ability.Enemy.Melee", "적 AI 근거리 공격")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Enemy_Boss_BurstShoot, "Ability.Enemy.Boss.BurstShoot", "보스 추적 조준 후 버스트 발사 공격")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Enemy_Boss_GroundSlam, "Ability.Enemy.Boss.GroundSlam", "보스 지면 강타 도넛 공격")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Enemy_Boss_Laser, "Ability.Enemy.Boss.Laser", "보스 지속 레이저 공격")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(Ability_Enemy_Boss_SphereScatter, "Ability.Enemy.Boss.SphereScatter", "보스 포물선 구체 분산 공격")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(GameplayCue_Enemy_Boss_BurstCharge, "GameplayCue.Enemy.Boss.BurstCharge", "보스 버스트 공격 차지 연출")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(GameplayCue_Enemy_Boss_LaserCharge, "GameplayCue.Enemy.Boss.LaserCharge", "보스 레이저 예고 및 충전 연출")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(GameplayCue_Enemy_Boss_LaserPreview, "GameplayCue.Enemy.Boss.LaserPreview", "보스 레이저 고정 경로 예고 연출")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(GameplayCue_Enemy_Boss_LaserFire, "GameplayCue.Enemy.Boss.LaserFire", "보스 레이저 발사 연출")
UE_DEFINE_GAMEPLAY_TAG_COMMENT(GameplayCue_Player_GrapplingHook, "GameplayCue.Player.GrapplingHook", "플레이어 그래플링 와이어 연출")
}
