#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"

namespace LastFPSGameplayTags
{
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Dead);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Crouched);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Sprinting);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Type_Boss);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AuraDamageCooldown);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Freeze);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_FreezeStack);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Slow);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_SpeedBoost);

	// 레벨 규칙으로 부여되는 전투 금지 상태. 전투 어빌리티의 ActivationBlockedTags 가 참조한다.
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Disabled);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_KnockedDown);

	// 퀘스트 목표 구역 태그 (도달/수호/점령). 코드가 값을 직접 참조하진 않지만 프로젝트 방침대로 네이티브로 관리.
	// 새 구역 추가 = 여기 한 줄 + .cpp 정의 (재컴파일 필요). 배치·DataTable 은 이 태그를 태그 피커로 선택한다.
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Location_Quest_Depot);		// 위치 도달(ReachLocation) - 보급창고
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Location_Quest_Reactor);		// 수호(DefendZone) - 리액터
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Location_Quest_Outpost);		// 점령(CaptureZone) - 전초기지

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_Dash);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill1);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill2);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill3);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ultimate);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_CriticalHit);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Parameter_AreaDuration);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Parameter_DamageInterval);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Parameter_ConeAngle);

	// 무기 밸런스 행의 Parameters 맵에서 사용하는 키. 공통 행 구조를 바꾸지 않고 무기 고유 수치를 표현한다.
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Parameter_PelletCount);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Parameter_SpreadHalfAngle);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Parameter_SpreadADSMultiplier);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Parameter_SpreadBloomPerShot);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Parameter_SpreadBloomMax);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Parameter_SpreadBloomRecovery);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_AbilityCommit);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_AbilityEnd);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_ProjectileSpawn);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_MeleeHit);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_MeleeTrace);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_MeleeTrace_Begin);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_MeleeTrace_Tick);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_MeleeTrace_End);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_GroundSlamImpact);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_ViolaIceAuraEffect);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_ViolaFrostStormEffect);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_IceStormSpawn);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_GrapplingHookPull);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Enemy_WeakpointBroken);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_HUD_Visible);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Sprint);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ADS);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Dash);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Fire);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Reload);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Scoreboard);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill1);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill2);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill3);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ultimate);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_GrapplingHook);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_WeaponSlot1);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_WeaponSlot2);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Jump);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_DoubleJump);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reload);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill1);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill2);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill3);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Ultimate);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_GrapplingHook);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ProbePassive);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Trigger_SpawnProbe);

	// 적 AI 공격 어빌리티
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Shoot);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Melee);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Boss_BurstShoot);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Boss_GroundSlam);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Boss_Laser);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Boss_SphereScatter);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Boss_WeakpointKnockdown);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Enemy_Boss_BurstCharge);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Enemy_Boss_LaserCharge);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Enemy_Boss_LaserPreview);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Enemy_Boss_LaserFire);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Enemy_Boss_SpawnDissolve);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Player_GrapplingHook);
}
