#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"

namespace LastFPSGameplayTags
{
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Dead);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Crouched);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AuraDamageCooldown);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Freeze);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_FreezeStack);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_Dash);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill1);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill2);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill3);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ultimate);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_CriticalHit);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_AbilityCommit);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_AbilityEnd);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_ProjectileSpawn);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_ViolaIceAuraEffect);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_ViolaFrostStormEffect);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_IceStormSpawn);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_HUD_Visible);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Sprint);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ADS);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Dash);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Fire);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Reload);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Scoreboard);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill1);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill2);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Skill3);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ultimate);

	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Jump);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_DoubleJump);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fire);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Reload);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill1);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill2);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Skill3);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Ultimate);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ProbePassive);
	LASTFPS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Trigger_SpawnProbe);
}
